name = "CustomVertexGraphs"
uuid = "15d1ea5b-2f35-4b4e-be9b-b299fe0fbdd5"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.0.1"

[deps]
AbstractBijections = "de08f535-130b-4136-8868-16b4854ff79a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
Dictionaries = "0.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
